### ISSUE TITLE
Mitgrate IEMRE to a database

### ISSUE THREAD

**Issue by akrherz** [akrherz/iem#199]
The usage of netcdf as the primary data store for IEMRE data has become untenable. In another lifetime, with a better developer, perhaps this would not have ended in tears.  So here we are, gonna dump all this into the PostGIS database and migrate things over to using it as time allows.  Will keep the netcdf files around as a downstream product of the database.

So our TODO list includes:

 - [x] create database and schema
 - [x] database write from various analysis scripts
 - [x] a sync script that does one-way copy from database to netcdf
 - [x] migrate various apps and services to use the database
 - [ ] reimplement the `hasdata` concept, this was stored in the netcdf files and used as the `domain`
 - [x] hope this all works out

Initial dev laptop load of 2019 daily data took about an hourly and yielded a database table about 3 GB in size.

**Comment by akrherz** [comment]
The initial foray into this work did not go very well.  My development laptop struggled to copy the netcdf data into the database and the resulting table/index size was disconcerting.  I should have expected as such as the currently hourly netcdf files are 17 GB in size and the database looked to be around 30 GB per year.  Using variable size squeezing techniques is not too appealing.  Am boggling some more on this....

**Comment by akrherz** [comment]
Initial database load failure
```
$ python copy_to_database.py 2018 hourly
  0%|                                                                                         | 0/8760 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "copy_to_database.py", line 52, in <module>
    main(sys.argv)
  File "copy_to_database.py", line 46, in main
    null='null')
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "9.0"
```

**Comment by akrherz** [comment]
So just migrating the daily data to postgresql was 600 GB.  It would likely be tight to make all the hourly data fit too.  Looking at my code, I am unsure if migrating the hourly data is a big deal at the moment as I don't really use the hourly data in places that are hurt by the thread-unsafe netcdf access.

**Comment by akrherz** [comment]
So I pushed the code to the IEM that makes this regime change live for the daily data.  The hourly data is too much for the backend database to deal with for now.  The netcdf files continue to be synced from the database, so the blast radius is somewhat low for this.  Will wrap this up for now and whack-a-mole anything that subsequently breaks.
